sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
before_install:
  - gem install sass
  - gem install compass
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
